# Generated by Django 5.0 on 2023-12-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
