# Generated by Django 5.0 on 2023-12-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
