# Generated by Django 5.0 on 2023-12-13 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_accepted_done_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('job', 'provider')},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider')),
            ],
            options={
                'unique_together': {('client', 'provider')},
            },
        ),
    ]
