# Generated by Django 5.0 on 2023-12-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_client_image_provider_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(null=True, upload_to='providers/'),
        ),
    ]
