# Generated by Django 5.0 on 2023-12-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_client_image_alter_provider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='image',
            new_name='client_image',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='image',
            new_name='provider_image',
        ),
    ]
