# Generated by Django 5.0 on 2023-12-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_image_client_client_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider_image',
            new_name='image',
        ),
    ]
