# Generated by Django 5.0 on 2023-12-15 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_client_image_client_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider')),
            ],
            options={
                'unique_together': {('client', 'provider')},
            },
        ),
    ]
