# Generated by Django 5.0 on 2023-12-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='done',
            name='client_done',
        ),
        migrations.RemoveField(
            model_name='done',
            name='provider_done',
        ),
        migrations.AddField(
            model_name='accepted',
            name='client_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accepted',
            name='provider_done',
            field=models.BooleanField(default=False),
        ),
    ]
