# Generated by Django 5.0 on 2023-12-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_done_client_done_remove_done_provider_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='value',
        ),
    ]
