# Generated by Django 5.0 on 2023-12-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_review_unique_together_review_client_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
