# Generated by Django 5.0 on 2023-12-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('client', 'provider')},
        ),
    ]
