# Generated by Django 5.0 on 2023-12-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
    ]
